### ISSUE TITLE
The ability to enter text..

### ISSUE THREAD

**Issue by epic6666** [unruhschuh/MrWriter#20]
..would be greatly appreciated. I see a fork here has (apparently) already implemented it: https://github.com/AlexD97/MrWriter
Perhaps you can cannibalize the code from it? A decent method for text-entry is all this program needs to be a OneNote killer tbh.
Thanks for your work!

**Comment by unruhschuh** [comment]
I'm currently working on adding images (jpg, png,...). Text is next, but I cannot make a promise as to when that'll happen.

Images btw are a prerequisite to text, since I'll render the text as an image and I want text to be rotatable/resizable.

**Comment by unruhschuh** [comment]
Duplicate of #16

**Comment by unruhschuh** [comment]
Text is here! Let me know what you think.

![screenshot 2019-02-02 at 10 40 35](https://user-images.githubusercontent.com/13489581/52162670-c2d3df00-26d7-11e9-812f-3437779c3143.png)

**Comment by unruhschuh** [comment]
This is fun
![screenshot 2019-02-02 at 11 19 30](https://user-images.githubusercontent.com/13489581/52163058-fbc28280-26dc-11e9-8d77-9297498377fa.png)
